exported transactions will be tagged with +COIN

diff --git a/bin/coin b/bin/coin
--- a/bin/coin
+++ b/bin/coin
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+if [[ "$1" == 'debug' ]]; then shift ; set -x ; fi
+
 VERSION='0.2.0'
 
 # Entry point to my program. Loads config.yml then routes to the appropriate subprogram as instrcuted
@@ -8,12 +10,19 @@ VERSION='0.2.0'
 # STATUS: NOTHING PLANNED
 # TESTS:  PASSED but undocumented
 
-ROOT_DIR=$( dirname "$(dirname "$(readlink -f "$0")")" )
+ROOT=$( dirname "$(dirname "$(readlink -f "$0")")" )
 
-source "$ROOT_DIR/src/dependency/manager.sh"
+set -o pipefail
+# set -u # example: /home/ahmad/bin/auto: line 23: ROOT: unbound variable, holy shit this is amazing
+# set -e # sideffects maybe
 
-CONFIGFILE="$ROOT_DIR/config.yml"
-HELPFILE="$ROOT_DIR/help.txt"
+export ROOT # don't fail me, the config loader relies on you!
+
+source "$ROOT/src/config-loader.sh"
+source "$ROOT/src/dependency/manager.sh"
+
+CONFIGFILE="$ROOT/config.yml"
+HELPFILE="$ROOT/help.txt"
 ARGS="$@"
 
 # Define options as an array to preserve spaces
@@ -24,15 +33,15 @@ COIN_OBJECTS=(
   "contract:contract"
 )
 
-CMD_ACCOUNT="$ROOT_DIR/src/account/manager.sh"
-CMD_TRANSAC="$ROOT_DIR/src/transaction/manager.sh"
-CMD_PLAN="$ROOT_DIR/src/pdplan/manager.sh"
+CMD_ACCOUNT="$ROOT/src/account/manager.sh"
+CMD_TRANSAC="$ROOT/src/transaction/manager.sh"
+CMD_PLAN="$ROOT/src/pdplan/manager.sh"
 
-CMD_BILL="$ROOT_DIR/src/task.sh" # FLAGGED FOR REMOVAL
-CMD_LIST="$ROOT_DIR/src/list.sh" # FLAGGED FOR REMOVAL
-CMD_TASK="$ROOT_DIR/src/task.sh" # FLAGGED FOR REMOVAL
-CMD_INSERT="$ROOT_DIR/src/insert.sh" # FLAGGED FOR REMOVAL
-CMD_BALANCE="$ROOT_DIR/src/balance.sh" # FLAGGED FOR REMOVAL
+CMD_BILL="$ROOT/src/task.sh" # FLAGGED FOR REMOVAL
+CMD_LIST="$ROOT/src/list.sh" # FLAGGED FOR REMOVAL
+CMD_TASK="$ROOT/src/task.sh" # FLAGGED FOR REMOVAL
+CMD_INSERT="$ROOT/src/insert.sh" # FLAGGED FOR REMOVAL
+CMD_BALANCE="$ROOT/src/balance.sh" # FLAGGED FOR REMOVAL
 
 DEFAULT_FN='undefined_function'  # Defined in config
 
@@ -53,9 +62,10 @@ dispatch() {
     help | --help | -h)     shift ; show_help    ;;
     ver* | --version | -v)  shift ; show_version ;;
 
-    # general
+    # special
       new) shift ; create_new_object "$@" ;;
     --dev) shift ; echo "DEV MODE: shortcut to gh and git to aid in development" ;;
+    export) shift ; do_transac export ;;
 
     # managers
     acc* | --account* | -A | bal*) shift ; do_account "$@" ;;
@@ -94,8 +104,8 @@ do_balance() { "$CMD_BALANCE" "$@" ; } # DEPRECATED
 # The original purpose of Coinmaster was simply to track bills deadlines and view account balances.
 # This summary adheres to this original purpose.
 do_summary() {
-  echo -e "Upcoming bills:"
-  do_transac +bill           # view upcoming bills
+  # echo -e "Upcoming bills:"
+  do_transac                 # view upcoming bills
   do_account balance --total # view total balance
   echo -e "\nDo \`coin acc\` to check balance"
 }
